name = "reunite-io"
main = "functions/_worker.js"

compatibility_date = "2024-03-18"

#pages_build_output_dir = "./public"

# This binding allows your Worker to access the D1 database.
[[d1_databases]]
binding = "DB"
database_name = "reunite-db"
database_id = "456edd48-d166-4845-87b9-c0195d4bce7c"
