# Top-level configuration
name = "reunite-io"
compatibility_date = "2025-07-18"
compatibility_flags = ["nodejs_compat"]

# This binding allows your Worker to access the D1 database.
[[d1_databases]]
binding = "DB"
database_name = "reunite-db"
database_id = "456edd48-d166-4845-87b9-c0195d4bce7c"
