# This is the configuration file for the Wrangler CLI.
# It defines the worker and the pages project settings.

# Name of your worker.
name = "reunite-io"
# The entry point for your worker.
main = "src/worker.js"

# Compatibility date is required. It ensures your worker runs on a stable version of the Workers runtime.
compatibility_date = "2023-10-30"

# Configuration for the Cloudflare Pages project.
[pages]
# The directory of static assets to upload.
upload_dir = "public"

# This binding allows your Worker to access the D1 database.
# The `binding` name must match the variable name used in your worker code (env.DB).
[[d1_databases]]
binding = "DB"
database_name = "reunite-db"
database_id = "456edd48-d166-4845-87b9-c0195d4bce7c"
